PACKAGE_NAME="t1-ibridge-cfg"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="ibridge-cfg"
DEST_MODULE_LOCATION[0]="/kernel/drivers/usb/misc"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
AUTOINSTALL="yes"
